XXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXX
  XXXXXXXXXX XXXXXX
  XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
  XXXXXXXXXXXX XXXX
  XXXXXXX XXXX XXXXX
X
XXXXXXXXXXXXXXXX X XXXX X
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXX XXXX
  XXXXXXXXX XXXXXXXXX
  XXXXXX XXXXXXXX
X
XXXXXXXXXXXXXXXX X XXXX X
  XXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXX
X
XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X
  XXXXXX XXXXXXXX
  XXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXX
X
XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X
  XXXXXX XXXXXXXX
  XXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXX
X
XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X
  XXXXXX XXXXXX
  XXXXXXX XXXXXX
  XXXXXXXXXXXXXX XXXXXX
X
XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX X
	XXXXXXXXXXXXXX XXX
	XXXXXXXXXXX
	XXXXXXXXX XXXXXXXXX
	XXXX XX XXXXX XX
	XXXXXX XXXXXXXX XXXXXXX XXXXXXXX
  XXXXXXXXXXXXXX XXXXXX
	XXXXXXXXXXX XXXXX XXXX X X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX X XXXX X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX XXXXX X X XXXXXXXXX XXXX XXXX XXXXX	
				XXXXX X XXXXX X XXXXXXXXX XXXX XXXX XXXXX
  XXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXX
X
XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X
	XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
	   XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
			XXXXXXXXXX XXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXX
    XXXXX XXXXXXXX
X
XXXXXXXXXX XXXXXXXXXXXXXX X
  XX X
    XXXXXXXXXXX XXXXX XXXX X X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX X XXXX X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX XXXXX X X XXXXXXXXX XXXX XXXX XXXXX	
				XXXXX X XXXXX X XXXXXXXXX XXXX XXXX XXXXX
  X
  XXX X
    XXXXXXXXXXX XXXXX XXXX X X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX X XXXX X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX XXXXX X X XXXXXXXXX XXXX XXXX XXXXX	
				XXXXX X XXXXX X XXXXXXXXX XXXX XXXX XXXXX
  X
  XXX X
     XXXXXXXXXXX XXXXX XXXX X X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX X XXXX X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX XXXXX X X XXXXXXXXX XXXX XXXX XXXXX	
				XXXXX X XXXXX X XXXXXXXXX XXXX XXXX XXXXX
  X
  XXX X
   XXXXXXXXXXX XXXXX XXXX X X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX X XXXX X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX XXXXX X X XXXXXXXXX XXXX XXXX XXXXX	
				XXXXX X XXXXX X XXXXXXXXX XXXX XXXX XXXXX
  X
  XXXX X
    XXXXXXXXXXX XXXXX XXXX X X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX X XXXX X XXXXXXXXX XXXX XXXX XXXXX
				XXXXX XXXXX X X XXXXXXXXX XXXX XXXX XXXXX	
				XXXXX X XXXXX X XXXXXXXXX XXXX XXXX XXXXX
  X
X
XXXXXXXXXX XXXXXXXXXXXX X
  XX X
    XXXXXX XXXXXXXX
  X
  XXX X
    XXXXXX XXXXXXXX
  X
  XXX X
    XXXXXX XXXXXXXX
  X
  XXX X
    XXXXXX XXXXXXXX
  X
  XXXX X
    XXXXXX XXXXXXXX
  X
X
XXXXXXXXXX XXXXXXXXXXXXX X
  XX X
    XXXXXX XXXXXXXX
  X
  XXX X
    XXXXXX XXXXXXXX
  X
  XXX X
    XXXXXX XXXXXXXX
  X
  XXX X
    XXXXXX XXXXXXXX
  X
  XXXX X
    XXXXXX XXXXXXXX
  X
X

XX XXXX XXXXX XX
X X
    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
X
XXXX X
  XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXXXXXXXXXX XXXXX
X
XXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXX X
    XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
    XXXXXX XXXXXXXX
X
XX X
  XXXXXXXXXXX XXXXXXX
  XXXXXXX XXXX XXXXX
X
XXXXXXXXXX X 
  XXXXXXXXXX XXXXXX
  XXXXXXX XXXX XXXX XXXXX
  XXXXXXXXXX XXXXX
  XXXXXXXXXXX XXXXXXX
X
XXXXXXXXXXXXXXX X
  XXXXXXXXXXX XXXXXXX
X
XXXXXXXXXXX X
  XXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX XXXX
X
XXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
  
  XXXXXXXXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXX
XXXXXXXXXX