# Generated by Django 2.0.2 on 2018-05-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('Phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('FullAddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Quote', models.CharField(blank=True, max_length=400, null=True, verbose_name='Quote')),
                ('Introduction', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Presentation')),
                ('HasFacebook', models.BooleanField(verbose_name='Facebook')),
                ('HasTwitter', models.BooleanField(verbose_name='Twitter')),
                ('HasLinkedIn', models.BooleanField(verbose_name='LinkedIn')),
                ('HasGitHub', models.BooleanField(verbose_name='GitHub')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolName', models.CharField(max_length=200, verbose_name='School Name')),
                ('DegreeName', models.CharField(max_length=200, verbose_name='Degree Name')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
                ('DegreeDescription', models.TextField(verbose_name='Description')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('LogoURL', models.CharField(default='put a URL', max_length=200, verbose_name='Logo URL')),
                ('curriculum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maincv.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('Company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('ExperienceDescription', models.TextField(verbose_name='Job Description')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
                ('IsCurrent', models.BooleanField(default=False, verbose_name='Is my current job')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maincv.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(blank=True, max_length=200, null=True, verbose_name='Level')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maincv.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Skill Name')),
                ('HtmlCode', models.TextField(verbose_name='Html Code')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maincv.Technology'),
        ),
    ]
