# Generated by Django 2.0.2 on 2018-07-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincv', '0003_auto_20180705_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience',
            new_name='profile',
        ),
    ]
