# Generated by Django 2.0.2 on 2018-10-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincv', '0008_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='test', max_length=100, verbose_name='Service Title'),
            preserve_default=False,
        ),
    ]
