# Generated by Django 2.0.2 on 2018-11-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincv', '0009_auto_20181031_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Add description'),
        ),
    ]
