# Generated by Django 2.0.2 on 2018-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincv', '0010_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainTitle', models.CharField(max_length=200, verbose_name='Main Title')),
            ],
        ),
    ]
