# Generated by Django 2.1.3 on 2018-12-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincv', '0012_auto_20181210_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, verbose_name="Reference's name")),
                ('role', models.CharField(max_length=200, verbose_name='Reference Role')),
                ('company', models.CharField(max_length=200, verbose_name='Company name')),
                ('content', models.TextField(default='Good Work')),
            ],
        ),
    ]
