# Generated by Django 2.1.3 on 2018-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincv', '0013_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.CharField(default='path/to/image', max_length=200, verbose_name="Image's URL"),
        ),
    ]
