BBBB BBBBBB
XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXX
    XXXX XXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXX XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
        XX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX FFFFXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX
