BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX  
    XXXX XXXXXXXXXX XXX XXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
         #

        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
          XXXX XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXBBBBBBBBBB
          BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
            
          BBBBBB
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
              
              BBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          BBBBBB
          XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXX
