BBBB BBBBBB
XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXX
    XXXX XXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXX XXXXXXXXXXXXX
    BBB BBB BB BBBBBBBBBB
    XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXX XXXXXXXX
       #
 #
 #

      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX FFFFXXXXXX
        XXXX  FFFF XXX
      XXXXXX
    XXXXXX
    BBBBBB
  XXXXXX
XXXXXXXXXX

