XXXXXXXXXXXX XXXX XXXXXXXX X XXXXX XXXXXXXX
XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXX
    XXXX XXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
    XXX XXXXXXXXXXXXX
    XXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXX XXXXXXXX
      XXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXX
        BBB BBB BB BBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXX XXXXXXX  XXX
           #
  
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFF FF X FFFFFFF FFXXXXXX
            XXXXXX
           #

          XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
             FFFF
          XXXXXX
        XXXXXX
        BBBBBB
      XXXXXX
      XXXXXXXXX XXXXXXXXX
    XXXXXX
  XXXXXXXXX XXXXXX
  XXXXXX
XXXXXXXXXX
XXXXXXXXXXXX XXXX XXXXXXXX X XXXXX XXXXXXXX
