BBBB BBBBBB
XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXX
    XXXX XXXXXXXXXXX XXX XXX XXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
      XXXXXX
    XXXXXX
XXXXXXXXXX
